# Generated by Django 5.0.6 on 2024-05-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
